name: cloudrun-deploy

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: us-gcp-ame-con-116-npd-1
    SERVICE_NAME: smartbookmark-backend
    REGION: us-west2
    PRODUCT: smartbookmark

on: 
  push: 
    branches:
#       - main
      - new

jobs:
  setup-build-deploy:
    name: Cloud Run Deploy
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
            gcloud config set project $PROJECT_ID
      - name: Image
        run: |-
          docker build -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME ./Sample-App
          
      #Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
            gcloud auth configure-docker -q
        # Push image to Google Container Registry
      - name: Build
        run: |-
            docker push asia.gcr.io/$PROJECT_ID/$SERVICE_NAME
      - name: Deploy
        run: |
            gcloud run deploy $SERVICE_NAME --min-instances=1 --max-instances=2 --memory=512Mi  --cpu=1 --region $REGION --image asia.gcr.io/$PROJECT_ID/$SERVICE_NAME --allow-unauthenticated
